# create a array from python list

In [1]:
import numpy as np

In [2]:
py_list = [1,2,3,4,5,6]
py_list2 = [1,2,3,4,5,"mit"]

print(py_list , type(py_list))
print(py_list2 , type(py_list2))

[1, 2, 3, 4, 5, 6] <class 'list'>
[1, 2, 3, 4, 5, 'mit'] <class 'list'>


In [3]:
np_arr = np.array(py_list)
np_arr2 = np.array(py_list2)

print(np_arr , type(np_arr) , np_arr.dtype)
print(np_arr2 , type(np_arr2) , np_arr2.dtype)

print(np_arr[0] , type(np_arr[0]))
print(np_arr2[0] , type(np_arr2[0]))

# print dimension of srray
print(np_arr.shape)
print(np_arr2.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'mit'] <class 'numpy.ndarray'> <U21
1 <class 'numpy.int64'>
1 <class 'numpy.str_'>
(6,)
(6,)


# make 2D Array


In [4]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2D)
print(type(arr2D))
print(arr2D.dtype)
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)


# Build Array using In build Functions

In [5]:
# fill with zeros
b = np.zeros(10)
print(b)
print(b.dtype)

# make 2d array and set data type
c = np.zeros((10,10) , dtype = "int64")
print(c)
print(c.dtype)

# fill with ones
d = np.ones(10)
print(d)
print(d.dtype)

# fill with given value
e = np.full((3,3),100)
print(e)
print(e.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
int64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
[[100 100 100]
 [100 100 100]
 [100 100 100]]
int64


In [6]:
# identity metric :
# this is a square matrix
# all diagonal values are 1
# other all are 0
#  1 0 0
#  0 1 0
#  0 0 1


f = np.eye(4) # pass size of matrix
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# range (start ,end , step)

g = np.arange(1,11,1)
print(g , g.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [ ]:
#  make evenly space array

# linspace(start ,end , size) (end will be include here)
h = np.linspace(0,100,5)
print(h ,h.shape)

[  0.  25.  50.  75. 100.] (5,)


# Properties Of Array

In [ ]:
arr = np.array([[1,2,3],[4,5,6,],[7,8,9]])

print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


# Operations on Arrays

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
# reshaping
print(arr1 , arr1.shape)

reshape_arr = arr1.reshape((3,2))
print(reshape_arr ,reshape_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [ ]:
# indexing
print("\nindexing")
print(arr1[1])
print(arr1[0])
print(arr1[0][0])
print(arr1[1][2])

# fancy indexing
# access multiple index value at a time
print("\nFacny Indexing")
arr2 = np.array([1,2,3,4,5,6,7,8,9])
inx = [0 , 1 ,5 ,7]
print(arr2[inx])

# boolean indexing
# base on conditions , if ture thrn retunr that index value
print("\nBoolean Indexing")
print(arr2[arr2 > 3])



indexing
[4 5 6]
[1 2 3]
1
6

Facny Indexing
[1 2 6 8]

Boolean Indexing
[4 5 6 7 8 9]


In [ ]:
# slicing
# arr2 = np.array([1,2,3,4,5,6,7,8,9]) (previouslly define)

# [start , end , step]
print(arr2[1:5])
print(arr2[2:])
print(arr2[:6])
print(arr2[1:8:2])
print(arr2[::4])


# important note : copy vs view
# Python list slicing creates a new copy of the selected elements, so any changes made to the sliced list do not affect the original list.
# In contrast, NumPy array slicing usually creates a view of the original array, which shares the same memory.
# Therefore, changes made to the sliced NumPy array are also reflected in the original array.
# If an independent copy is needed in NumPy, the .copy() method must be used.

[2 3 4 5]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6]
[2 4 6 8]
[1 5 9]
